(function(e){var k=window.AmazonUIPageJS||window.P,l=k._namespace||k.attributeErrors,b=l?l("WebFlowIngressJs",""):k;b.guardFatal?b.guardFatal(e)(b,window):b.execute(function(){e(b,window)})})(function(e,k,l){e.when("jQuery").register("webflow-fetch-experience",function(b){return{fetchExperience:function(b){return fetch(b,{headers:{Accept:"application/vnd.com.amazon.xa+html"}}).then(function(b){if(b.ok)return b.text();throw Error("Network response: "+b.status);}).then(function(b){return{html:b}}).catch(function(b){return{error:b}})},
buildExperienceUrl:function(e,h){var d=new URL(e,k.location);(new URLSearchParams(b.param(h))).forEach(function(b,a){d.searchParams.set(a,b)});return d.toString()}}});e.when("A","a-modal-framework","a-modal-framework-constants").register("webflow-modal",function(b,e,h){return{presentModal:function(d){d={type:"ajax",source:d};var g='\x3cdiv class\x3d"'+h.CONTENT_WRAPPER_CLASS+'"\x3e\x3c/div\x3e';g=b.$('\x3cdiv style\x3d"background-color:white" class\x3d"overlay-container"\x3e\x3c/div\x3e').append("",
'\x3cbutton class\x3d"overlay-close"\x3e\x3cspan class\x3d"a-icon a-icon-close-white"\x3e\x3c/span\x3e\x3c/button\x3e').append(g);d=new e(g,d,{dismissStrategy:"transient",scrimType:"translucent"});d.present();d=d._frameworkWrapper.find(".overlay-close");b.declarative.create(d,"a-modal-framework-dismiss");b.declarative("a-modal-framework-dismiss",["click","keydown"],function(a){var d=b.$(a.$currentTarget).closest("."+constants.FRAMEWORK_WRAPPER_CLASS);if(0!==d.length&&(d=d.data("overlayInstance"))){var c=
"keydown"===a.type&&a.$event.which===b.constants.keycodes.ESCAPE;("click"===a.type||"persistent"!==d._dismissStrategy&&c)&&d.dismiss()}})}}});e.when().register("webflow-bottomsheet",function(){return{isBottomSheetOpen:function(){return!1},closeBottomSheetAndRedirect:function(b){e.logError(null,"closeBottomSheetAndRedirect called on desktop - this should not happen","ERROR")}}});e.when("webflow-modal","webflow-bottomsheet","webflow-fetch-experience").register("webflow-routing",function(b,m,h){function d(a){try{k.top.location.href=
a}catch(f){e.logError(f,"Could not change the URL in the parent window:"+a,"ERROR")}}function g(a){a&&"function"===typeof a&&a()}return{show:function(a){try{var f=null;"url"in a.route?f=a.route.url:"web"in a.route&&"url"in a.route.web?f=a.route.web.url:"flow"in a.route&&(f=h.buildExperienceUrl(a.route.flow.endpoint,a.route.flow.inputs));if(null===f)throw Error("Invalid Options Error: no url found");var c=f;"bottom-sheet"==a.presentationConfig.presentationType&&m.presentBottomSheet(c,a.presentationConfig.bottomSheetConfig);
"modal-with-overlay"==a.presentationConfig.presentationType&&b.presentModal(c);"push"==a.presentationConfig.presentationType&&(m.isBottomSheetOpen()?m.closeBottomSheetAndRedirect(c):a.route.url?d(c):a.route.web.url?d(c):(e.logError(null,"fullUrl not available:"+c+", navigating to fallbackUrl","WARN"),d(a.route.flow.fallbackUrl)));g(a.successCallback)}catch(n){throw g(a.failCallback),n;}}}});e.declare("webflow-skeleton-tmp-icdp",{getSkeleton:function(){function b(){var b=a();b.append(c(["webflow-skeleton-tmp-icdp-text-extra-large",
"a-spacing-mini"]),c(["webflow-skeleton-tmp-icdp-text-extra-large","a-spacing-mini"]),c(["webflow-skeleton-tmp-icdp-text-small"]));return b}function e(){var a=c(["a-section"]);a.append(c(["webflow-skeleton-tmp-icdp-image-block","a-spacing-base"]),c(["webflow-skeleton-tmp-icdp-image-swatches","aok-align-center-horizontally"]));return a}function h(){var b=c(),d=a();d.append(c(["webflow-skeleton-tmp-icdp-text-base","a-spacing-mini"]));b.append(f("hr",["a-spacing-mini"]),d,f("hr",["a-spacing-none"]));
return b}function d(){var b=c(),d=a(),e=a(),f=a(),g=a();d.append(c(["webflow-skeleton-tmp-icdp-text-tall-mini","a-spacing-mini"]),c(["webflow-skeleton-tmp-icdp-text-tall-small","a-spacing-mini"]),c(["webflow-skeleton-tmp-icdp-text-small"]));e.append(c(["webflow-skeleton-tmp-icdp-text-micro"]));f.append(c(["webflow-skeleton-tmp-icdp-text-extra-large","a-spacing-mini"]),c(["webflow-skeleton-tmp-icdp-text-extra-large"]));g.append(c(["webflow-skeleton-tmp-icdp-text-medium","a-spacing-mini"]),c(["webflow-skeleton-tmp-icdp-text-large"]));
b.append(d,e,f,g);return b}function g(){var a=c(["a-row","a-padding-base","webflow-skeleton-tmp-icdp-action-bar"]);a.append(c(["a-column","a-spacing-base","webflow-skeleton-tmp-icdp-button"]),c(["a-column","a-spacing-base","webflow-skeleton-tmp-icdp-button","a-span-last"]));return a}function a(){return c(["a-section","a-spacing-none","a-padding-base"])}function f(a,b){a=document.createElement(a);for(var c in b)a.classList.add(b[c]);return a}function c(a){return f("div",a)}return function(){var a=
document.createElement("div");a.append(b(),e(),h(),d(),g());return a}()}})});