(function(g){var k=window.AmazonUIPageJS||window.P,m=k._namespace||k.attributeErrors,f=m?m("NileInlineCustomerExperienceWidgetCommonAssets",""):k;f.guardFatal?f.guardFatal(g)(f,window):f.execute(function(){g(f,window)})})(function(g,k,m){g.now("nile-inline-error-chunk-handler").execute(function(f){f||g.when("A","nile-inline-loader-utils","nile-inline-element-prefix-utils","ready").register("nile-inline-error-chunk-handler",function(d,b,a){return{handleChunk:function(e,g){var c=a.prefixed("nile-inline-hidden");
if(d.$(a.prefixedId("nile-inline-answer-generic-error")).hasClass(c)){b.hideLoader();b.hideTrailingLoader();var h=a.prefixedId("nile-inline-answer-container");d.$(h).removeClass(c);h=a.prefixedId("nile-inline-answer-text-container-error");d.$(h).removeClass(c);d.$(h).addClass(a.prefixed("nile-inline-text-container-collapsed-error"));var f=a.prefixedId("nile-inline-ai-generated-label");"sensitive_chunk"===g?d.$(f).addClass(c):d.$(f).removeClass(c);d.$(h).html(e)}}}})});g.now("nile-inline-feedback-chunk-handler").execute(function(f){f||
g.when("A","nile-inline-element-prefix-utils","nile-inline-feedback-actions","ready").register("nile-inline-feedback-chunk-handler",function(d,b,a){return{handleChunk:function(e){e=d.$(e);d.$(b.prefixedId("nile-inline-feedback-container")).html(e);a.showFeedback();return e}}})});g.now("nice-srp-utils").execute(function(f){f||g.when("A","ready").register("nice-srp-utils",function(d){function b(l,a){l=(l||"").split(".").map(Number);for(a=(a||"").split(".").map(Number);l.length<a.length;)l.push(0);for(;a.length<
l.length;)a.push(0);for(var c=0;c<l.length;++c)if(l[c]!==a[c])return l[c]>a[c]?1:-1;return 0}function a(){var a=c();return"Amazon"===a.name||"Amazon.com"===a.name}var e=d.$,f=[],c=function(){var a;return function(){if(!a){var c=document.cookie.match(/(?:^|;)\s*amzn-app-id\s*=\s*([^\s;]+)/);c=c?c[1].split("/"):[];var b=/(?:^|;)\s*micron\s*=\s*1\s*(?:$|;)/.test(document.cookie);a={name:c[0],version:c[1],isMicron:b}}return a}}(),h=function(){var a;return function(){if(!a){var c=document.cookie.match(/(?:^|;)\s*session-id\s*=\s*([^\s;]+)/);
c&&(a=c[1])}return a}}(),g=function(){var a;return function(){if(!a){var c=document.cookie.match(/(?:^|;)\s*amzn-app-ctxt\s*=\s*\d\.\d?\s*([^\s;]+)/);if(c)try{a=JSON.parse(decodeURIComponent(c[1]))}catch(n){}}return a}}();return{getAppInfo:c,getAppSessionId:h,getAppContext:g,makeIdempotent:function(a){var c=!1;return function(){c||(a.apply(this,arguments),c=!0)}},makeRateLimited:function(a,c){var b=!1,d=e.extend(!0,{},{minPeriodInMilliseconds:2E3},c);return function(){b||a.apply(this,arguments);b=
!0;setTimeout(function(){b=!1},d.minPeriodInMilliseconds)}},idempotentDeclarative:function(a,c,b){function e(a,c,b){var e;d.declarative(a,c,function(a){e===m&&(e=a.type);a.type===e&&b(a)})}var h=a+c;f[h]||("click touchstart"===c||"touchstart click"===c?e(a,c,b):d.declarative(a,c,b),f[h]=!0)},goToUrl:function(a){k.location.href=a},isMshop:a,isAppXSupported:function(){var e=c();return a()&&e.version&&!e.isMicron?Number(e.version.split(".")[0])%2?0<=b(e.version,"15.11"):0<=b(e.version,"20.8"):!1},truncateURIComponent:function(a,
c,b){if(!a||encodeURIComponent(a).length<=c)return a;b=b||"…";c-=encodeURIComponent(b).length;for(var e="",d=0,h=a.length-1;d<=h;){var f=Math.floor((h+d)/2),g=a.slice(0,f);encodeURIComponent(g).length<=c?(e=g,d=f+1):h=f-1}return e+b},decodeHtmlEntities:function(a){var c=document.createElement("textarea");c.innerHTML=a;return c.value}}})});g.now("nile-inline-csm").execute(function(f){f||g.when("A","ready").register("nile-inline-csm",function(){function d(b,a,e){"function"===typeof uet&&(e?uet(b,a,
{wb:1},e):uet(b,a,{wb:1}))}return{recordRequestStart:function(b,a){"string"===typeof b&&b.trim()&&d("bb",b,a)},recordFirstInferenceLatency:function(b){"string"===typeof b&&b.trim()&&(d("be",b),"function"===typeof uex&&uex("ld",b,{wb:1}))},recordCsmCount:function(b){ue.count(b,1)}}})});g.now("nile-inline-csrf").execute(function(f){f||g.when("A","ready").register("nile-inline-csrf",function(d){return{getRawCsrfToken:function(b){return d.$(b).find("input[name\x3danti-csrftoken-a2z]").val()}}})});g.now("nile-inline-element-prefix-utils").execute(function(f){f||
g.when("ready").register("nile-inline-element-prefix-utils",function(){var d="";return{setupElementPrefix:function(b){d=b+"-"},prefixed:function(b){return d+b},prefixedId:function(b){return"#"+d+b}}})});g.now("nile-inline-loader-utils").execute(function(f){f||g.when("A","nile-inline-element-prefix-utils","ready").register("nile-inline-loader-utils",function(d,b){return{showTrailingLoader:function(){var a=b.prefixed("nile-inline-hidden");var e=b.prefixedId("nile-inline-feedback-container");(e=!d.$(e).hasClass(a)&&
0<d.$(e).children().length)||(e=b.prefixedId("nile-inline-answer-generic-error"),e=!d.$(e).hasClass(a)&&0<d.$(e).children().length);e||(e=b.prefixedId("nile-inline-answer-text-container-error"),e=!d.$(e).hasClass(a)&&0<d.$(e).children().length);e||d.$(b.prefixedId("nile-trailing-loader")).removeClass(a)},hideTrailingLoader:function(){var a=b.prefixed("nile-inline-hidden");d.$(b.prefixedId("nile-trailing-loader")).addClass(a)},showLoader:function(){var a=b.prefixed("nile-inline-hidden");d.$(b.prefixedId("nile-inline-data-container")).removeClass(a);
d.$(b.prefixedId("nile-inline-loader-spinner")).removeClass(a)},hideLoader:function(){var a=b.prefixed("nile-inline-hidden");d.$(b.prefixedId("nile-inline-loader-spinner")).addClass(a);d.$(b.prefixedId("nile-inline-data-container")).addClass(a)}}})});g.now("nile-inline-state-manager").execute(function(f){f||g.when("A","nile-inline-element-prefix-utils","ready").register("nile-inline-state-manager",function(d,b){function a(){return b.prefixed("nice-state")}return{getState:function(){d.state(a())||
d.state.parse();return d.state(a())},setState:function(b){d.state.replace(a(),b)},extend:function(b){d.state(a(),b)}}})});g.now("nile-inline-uuid-generator").execute(function(f){f||g.when("A","ready").register("nile-inline-uuid-generator",function(d){return{generateUuid:function(){function b(){var a=new Uint32Array(4);k.crypto.getRandomValues(a);var b=-1;return"xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx".replace(/[xy]/g,function(c){b++;var e=a[b>>3]>>b%8*4&15;return("x"===c?e:e&3|8).toString(16)})}function a(){function a(){return Math.floor(65536*
(1+Math.random())).toString(16).substring(1)}return a()+a()+"-"+a()+"-"+a()+"-"+a()+"-"+a()+a()+a()}return function(){return"undefined"!=typeof k.crypto&&"undefined"!=typeof k.crypto.getRandomValues?b():a()}}()}})});g.now("nile-inline-event-stream-builder").execute(function(f){f||g.when("A","jQuery","ready").register("nile-inline-event-stream-builder",function(d,b){function a(a){this.url=a;this.eventListeners={};this.connectionSuccessfullyClosedCallback=this.errorCallback=this.httpRequest=m}function e(a){var c=
a.newMessage();return function(b,d){if(0===b.length){if(c.type in a.eventListeners)a.eventListeners[c.type](c);c=a.newMessage()}else if(0<d){var e=b.slice(0,d);b=b.slice(d+(" "===b[d+1]?2:1));switch(e){case "data":c.data=c.data?c.data+"\n"+b:b;break;case "event":c.type=b;break;case "id":c.lastEventId=b;break;case "retry":e=parseInt(b,10),isNaN(e)||(c.retry=e,a.retryCallback(c.retry))}}}}function f(a){var c=0,b=-1,d=!1;return function(e){for(var f=e.length,g=c;c<f;){d&&"\n"===e[c]&&(g=++c);for(var h=
-1;c<f&&-1===h;++c)switch(e[c]){case ":":-1===b&&(b=c-g);break;case "\r":d=!0;h=c;break;case "\n":h=c}if(-1===h)break;a(e.slice(g,h),b);g=c;b=-1}g!==f&&0!==g&&(c=g)}}a.prototype.addEventListener=function(a,b){this.eventListeners[a]=b};a.prototype.setErrorCallback=function(a){this.errorCallback=a};a.prototype.setConnectionSuccessfullyClosedCallback=function(a){this.connectionSuccessfullyClosedCallback=a};a.prototype.newMessage=function(){return{lastEventId:"",type:"",data:""}};a.prototype.isSuccessfulStatusCode=
function(a){return 0===a||200<=a&&300>a};a.prototype.buildRequestStageChangeCallback=function(a){return function(){switch(a.httpRequest.readyState){case XMLHttpRequest.DONE:a.isSuccessfulStatusCode(a.httpRequest.status)?a.connectionSuccessfullyClosedCallback!==m&&a.connectionSuccessfullyClosedCallback():a.errorCallback!==m&&a.errorCallback()}}};a.prototype.buildOnProgressCallback=function(a,b){return function(){b(a.httpRequest.responseText)}};a.prototype.retryCallback=function(a){};a.prototype.startPostStream=
function(a,b,d){var c=f(e(this));this.httpRequest=new XMLHttpRequest;this.httpRequest.onreadystatechange=this.buildRequestStageChangeCallback(this);this.httpRequest.onprogress=this.buildOnProgressCallback(this,c);this.httpRequest.ontimeout=this.errorCallback;this.httpRequest.onerror=this.errorCallback;this.httpRequest.open("POST",this.url,!0);this.httpRequest.timeout=d;this.httpRequest.setRequestHeader("accept","text/event-stream");this.httpRequest.setRequestHeader("Content-Type","application/json");
this.httpRequest.setRequestHeader("anti-csrftoken-a2z",b);this.httpRequest.send(JSON.stringify(a))};a.prototype.close=function(a){this.httpRequest.onerror=function(){};this.httpRequest.abort()};return{buildStreamingEndpointCall:function(b){return new a(b)}}})});g.now("nile-inline-collapse-bottom-sheet").execute(function(f){f||g.when("A","nile-inline-element-prefix-utils").register("nile-inline-collapse-bottom-sheet",function(d,b){return{registerCollapseBottomSheetActions:function(){var a=b.prefixed("nile-inline-widget");
a=d.$("[data-component-type\x3d"+a+"]");if(1===a.length||1===a.parent().length){a=a.parent()[0];var e=!1;(new IntersectionObserver(function(a){e?a[0].isIntersecting?g.when("mash").execute(function(a){a.dispatchEvent({type:"nice:inViewPort"})}):g.when("mash").execute(function(a){a.dispatchEvent({type:"nice:outViewPort"})}):e=!0},{threshold:.05})).observe(a)}}}})})});
/* ******** */
'use strict';(function(d){var k=window.AmazonUIPageJS||window.P,l=k._namespace||k.attributeErrors,b=l?l("NileInlineCustomerExperienceWidgetDPXRexAssets@ask",""):k;b.guardFatal?b.guardFatal(d)(b,window):b.execute(function(){d(b,window)})})(function(d,k,l){d.now("askSearch").execute(function(b){b||d.when("A","jQuery","rufusAskExpander","ready").register("askSearch",function(h,e,a){function b(){d&&d.abort();e(".askAnswerContainer").remove()}var d;return{setupExpander:function(){a.setupDesktopSeeMoreLessToggle();
a.setupMobileExpander()},executeSearch:function(a,g,n){n&&b();a={indicator:e("#ask-only-spinner"),params:{asin:a,query:g,isBlue:n},timeout:1E4,success:function(c){b();e("#ask-answer-container").append(c);c=h.$("#ask-loaded-response-text").text();h.$("#dpx-rex-nile-loading-response").append(c)}};d=h.get("/rufus/web/askSearch",a)},clearSearch:b}})});d.now("rufusAskExpander").execute(function(b){b||d.when("A","jQuery","ready").register("rufusAskExpander",function(b,e){return{setupDesktopSeeMoreLessToggle:function(){e(document).delegate(".askSeeMore",
"click",function(a){e(a.currentTarget).closest(".askExpanderContainer").addClass("askExpanderExpanded");a.preventDefault()});e(document).delegate(".askSeeLess","click",function(a){e(a.currentTarget).parents(".askExpanderContainer").removeClass("askExpanderExpanded");a.preventDefault()})},setupMobileExpander:function(){b.on("a:expander:askMobileLiveSearchResultExpander:toggle:expand",function(a){a=a.expander.$expander;a.find(".askMobileLiveSearchResultHeaderTextExpanded").css("display","block");a.find(".askMobileLiveSearchResultHeaderTextCollapsed").hide()});
b.on("a:expander:askMobileLiveSearchResultExpander:toggle:collapse",function(a){a=a.expander.$expander;a.find(".askMobileLiveSearchResultHeaderTextExpanded").hide();a.find(".askMobileLiveSearchResultHeaderTextCollapsed").css("display","block")})}}})});d.now("askAbstractPostQuestion").execute(function(b){b||d.when("A","ready").register("askAbstractPostQuestion",function(b){var e=b.$,a={postQuestionTextInputSelector:"input",callbacks:{goodQuestion:function(){},badQuestion:function(){},emptyQuestion:function(){}}};
return{setup:function(d,h){var f=e.extend(!0,{},a,h),g=!1;if(f.modalName)b.on("a:popover:beforeShow:"+f.modalName,function(a){g=!1});if(f.bottomSheetName)b.on("a:sheet:beforeShow:"+f.bottomSheetName,function(a){g=!1});b.declarative(d,"click",function(){var a=e(f.postQuestionTextInputSelector).find("input").andSelf().filter("input").val();a||(a=e(f.postQuestionTextInputSelector).find("textarea").andSelf().filter("textarea").val());var c=e(f.formSelector+" .promptPostQuestionTextInput"),b=e(f.modalFormSelector+
" textarea");a=b.length?b.val():c.length?c.val():a;"undefined"===typeof a||a.match(/^\s*$/)?f.callbacks.emptyQuestion():g?f.callbacks.goodQuestion():-1===a.indexOf("?")&&-1===a.indexOf("؟")?(f.callbacks.badQuestion(),g=!0):f.callbacks.goodQuestion()})}}})});d.now("askPostQuestion").execute(function(b){b||d.when("A","askAbstractPostQuestion","nile-inline-csrf","nile-inline-state-manager","ready").register("askPostQuestion",function(b,d,a,k){function e(a){c(".askMobilePostQuestionSuccessContainer").find(".post-success-response").html(a);
g(".askMobilePostQuestionSuccessContainer")}function f(a){if(401===a.status||466===a.status)c(".askMobilePostQuestionFormInBottomSheet").submit();else{a=a.http.responseText;var b=c(".askMobilePostQuestionFailureContainer").find(".failureDefaultMsg");a&&0<a.length?(c(".askMobilePostQuestionFailureContainer").find(".failureResponseMsg").html(a),b.hide()):b.show();g(".askMobilePostQuestionFailureContainer")}}function g(a,b){b=b||c("#ask-mobile-post-question-modal-container");b.children().hide();a=b.find(a);
a.removeClass("aok-hidden");a.show()}function h(d,e,f){var m={};c.each(d.serializeArray(),function(a,b){m[b.name]=b.value});m.askAsin=k.getState().asin;b.post(d.attr("action"),{withCredentials:!0,params:JSON.stringify(m),paramsFormat:"json",headers:{"anti-csrftoken-a2z":a.getRawCsrfToken("#rufusInlineCsrfTokenContainer"),"Content-Type":"application/json"},timeout:1E4,indicator:c(".askMobilePostQuestionSpinner"),success:e,error:f})}var c=b.$,l=null,p=function(a){c("#ask-post-question-text-area").attr("aria-invalid",
"true");".askBadQuestionError"===a?c("#ask-post-question-text-area").attr("aria-describedby","ask-question-posting-description ask-bad-question-error"):".askEmptyQuestionError"===a&&c("#ask-post-question-text-area").attr("aria-describedby","ask-question-posting-description ask-empty-question-error");g(a,c(".askMobilePostQuestionMsgContainer"))},q={postQuestionTextInputSelector:"#ask-mobile-post-question-modal-container .askMobilePostQuestionInput",bottomSheetName:"ask-mobile-post-question-modal",
callbacks:{goodQuestion:function(){c("#ask-post-question-text-area").removeAttr("aria-invalid");c("#ask-post-question-text-area").attr("aria-describedby","ask-question-posting-description");c(".askMobilePostQuestionSubmitButtons").hide();c(".askMobilePostQuestionMsgContainer").children().hide();h(c(".askMobilePostQuestionFormInBottomSheet"),e,f)},badQuestion:function(){p(".askBadQuestionError")},emptyQuestion:function(){p(".askEmptyQuestionError")}}};return{registerDeclarativeActions:function(){var a=
function(){var a=c("*[id*\x3dask-mobile-post-question-modal]");1<a.length&&0<c(".a-sheet-content-container #ask-mobile-post-question-modal").length&&a.each(function(){0>=c(this).closest(".a-sheet-content-container").length&&c(this).remove()})},e=function(b){a();b=c("#dpx-rex-nile-search-text-input").val();if(l!==b){var d=c("#ask-mobile-post-question-modal-container .askMobilePostQuestionInput").find("input").andSelf().filter("input");d&&0!==d.length||(d=c("#ask-mobile-post-question-modal-container .askMobilePostQuestionInput").find("textarea").andSelf().filter("textarea"));
d.val(b);l=b}c(".askMobilePostQuestionMsgContainer").children().hide();g(".askMobilePostQuestionFormInBottomSheet");c(".askMobilePostQuestionSubmitButtons").show()};b.on("a:sheet:beforeShow:ask-mobile-post-question-modal",e);b.on("a:popover:beforeShow:ask-mobile-post-question-modal",e);b.declarative("ask-mobile-post-question-input-keyup","keypress",function(a){a&&a.$event&&13===a.$event.which&&a.$event.preventDefault()});d.setup("ask-mobile-post-question-submit",q)}}})})});
/* ******** */
'use strict';(function(c){var r=window.AmazonUIPageJS||window.P,u=r._namespace||r.attributeErrors,f=u?u("NileInlineCustomerExperienceWidgetDPXRexAssets@rufus",""):r;f.guardFatal?f.guardFatal(c)(f,window):f.execute(function(){c(f,window)})})(function(c,r,u){c.now("nile-inline-answer-chunk-handler").execute(function(f){f||c.when("A","jQuery","a-truncate","nile-inline-html-truncator","nile-inline-loader-utils","dpx-rex-nile-inline-display-utils","dpx-rex-markdown-renderer","ready").register("nile-inline-answer-chunk-handler",
function(a,m,f,h,k,b,e){function p(a){return a.filter('[id^\x3d"section_groupId_"]').map(function(){return this.id}).get()}function c(a,e){p(e).forEach(function(b){var g=e.filter("#"+b);b=a.find("#"+b);if(b.length){var l=parseInt(b.attr("data-ask-sequenceId")),h=parseInt(g.attr("data-ask-sequenceId"));if(isNaN(l)||isNaN(h)||l<=h)b.html(g.html()),b.attr("data-ask-sequenceId",g.attr("data-ask-sequenceId"))}else a.append(g)})}var q=a.$("#dpx-rex-nile-inline-see-more-outer");return{handleChunk:function(a,
g){if("Carousel-related_questions_carousel_horizontal"===(g&&g.sectionMetadata&&g.sectionMetadata.type?g.sectionMetadata.type:u))return a=m(a),m("#dpx-rex-nile-inline-followon-pills-outside-container").html(a),a;g=a;a=m("#dpx-rex-nile-inline-answer-text-container");if(g=g.trim()){k.hideLoader();b.show("#dpx-rex-nile-inline-answer-container");var l=m(g);g=l[0]&&l[0].dataset.askBlueChunkType?l:m("\x3cdiv/\x3e").append(g);c(a,m(g));e.renderMarkdownContent(a);h.maybeTruncate(a,q,9)}else a=void 0;return a}}})});
c.now("nile-inline-chunk-renderer").execute(function(f){f||c.when("A","nile-inline-answer-chunk-handler","nile-inline-error-chunk-handler","nile-inline-feedback-chunk-handler","nile-inline-state-manager","dpx-nile-inline-constants").register("nile-inline-chunk-renderer",function(a,m,f,h,k,b){return{renderChunk:function(a,c){c.beforeChunk(a);if("CONTEXT_CHUNK"===a.type)a=JSON.parse(a.data).requestContext,k.getState()&&a&&k.extend({conversationHistoryId:a.conversationHistoryId,requestId:a.requestId});
else if("chunk"===a.type){var e=JSON.parse(a.data),p=e.htmlRenderedChunk;if(p){var x=null;if("text"===a.lastEventId)x=m.handleChunk(p,e);else if("feedback_chunk"===a.lastEventId)x=h.handleChunk(p);else if("sensitive_chunk"===a.lastEventId||"softlanding_error_chunk"===a.lastEventId||"internal_error_chunk"===a.lastEventId)k.extend({streamingState:b.streamingState.ERROR}),f.handleChunk(p,a.lastEventId);c.afterChunkRender(a,x)}}}}})});c.now("dpx-rex-nile-inline-widget-instrumentation").execute(function(f){f||
c.when("A","nice-srp-utils","nile-inline-state-manager","ready").register("dpx-rex-nile-inline-widget-instrumentation",function(a,m,p){function h(d){var a=Array.from(arguments).slice(1,arguments.length);return function(){for(var n=arguments.length,b=Array(n),e=0;e<n;e++)b[e]=arguments[e];d.apply(void 0,a.concat(b))}}function k(d){d=[d.dataset.blueMetrics,d.dataset.actionId];d=d.filter(function(d){return d!==u&&null!==d&&""!==d});return d.join(":")}function b(d){for(var a=Object.keys(d),b=0;b<a.length;b++){var e=
a[b],g=d[e];null===g||g===u?g="":"number"===typeof g&&(g=g.toString());d[e]=g}return d}function e(d,a){var n=m.getAppInfo(),e=m.getAppContext(),g=p.getState();d=Object.assign({timestamp:t(new Date),producerId:"mshop-nile",metadata:'{"program":"BLUE_DPX"}',isBeta:!1,deviceTypeId:e&&e.di&&e.di.dti||"",directedCustomerId:g.directedCustomerId||"",appVersion:n&&n.version||"",locale:g.locale||"UNKNOWN",marketplaceId:g.marketplaceId||"UNKNOWN",uxSessionId:"",sessionId:m.getAppSessionId()||""},d);"undefined"!==
typeof ue&&ue.event(b(d),"mshop-nile",a)}function c(d,a){"CONTEXT_CHUNK"===a.type?d.requestId||(d.requestId=JSON.parse(a.data).requestContext.requestId,v(d,d.actionId||"ANSWER"),d.searchTrigger!==u&&e({schemaId:"mshop.nile.events.4",eventTimeUTC:t(d.requestStartAt),nileRequestId:d.requestId,clickstreamRequestId:null,eventName:"SEARCH_TRIGGER",eventDetail:d.searchTrigger},"mshop.nile.events.4")):"chunk"===a.type&&O.includes(a.lastEventId)&&d.chunks.addFromEvent(a)}function f(d,a){if(a=a[0])a.isIntersecting||
!d.answer.impressingStartAt?d.answer.impressingStartAt=new Date:(d.answer.impressingEndAt=new Date,0===a.boundingClientRect.width&&0===a.boundingClientRect.height?A(d,"SEARCH_RESULTS_CLEARED"):A(d,"SCROLLED_AWAY"),d.answer.impressingStartAt=null,d.answer.impressingEndAt=null)}function q(d,a){var n=d.luggage,b=n.items[d.key];if(a=a[0])a.isIntersecting?(b.impressingStartAt=new Date,n.visibleElems.add(b.key)):b.impressingStartAt&&(b.impressingEndAt=new Date,b.reason=0===a.boundingClientRect.width&&0===
a.boundingClientRect.height?"SEARCH_RESULTS_CLEARED":"SCROLLED_AWAY",B(d),b.impressingStartAt=null,b.impressingEndAt=null,n.visibleElems.remove(b.key))}function C(d){var a=d.luggage.items[d.key];a.impressingStartAt&&"visible"!==document.visibilityState&&(document.contains(a.elem)&&(a.impressingEndAt=new Date,a.reason="PAGE_HIDDEN",B(d)),document.removeEventListener("visibilitychange",a.pageVisibilityChangeListener))}function g(d){d.answer.impressingStartAt&&"visible"!==document.visibilityState&&(d.answer.impressingEndAt=
new Date,A(d,"PAGE_HIDDEN"),d.answer.observer.unobserve(d.answer.elem),document.removeEventListener("visibilitychange",d.answer.visibilityChangeListener))}function l(d,a,b){b=b.find("[data-blue-metrics]");var n=h(U,d);d.visibilityChangeListenerForLatency=n;document.addEventListener("visibilitychange",d.visibilityChangeListenerForLatency);(n=document.getElementById("dpx-rex-nile-search-text-input"))&&!n.hasAttribute("listenerOnFocus")&&(n.addEventListener("touchend",h(r,d)),n.setAttribute("listenerOnFocus",
"true"));(n=document.getElementById("dpx-rex-nice-clear-button"))&&!n.hasAttribute("listenerOnErase")&&(n.addEventListener("touchend",h(J,d)),n.setAttribute("listenerOnErase","true"));y(d);for(n=0;n<b.length;n++){var e=b[n],g=k(e);d.items[g]?(d.items[g].elem&&d.items[g].elem.observer&&d.items[g].elem.observer.disconnect(),d.items[g].elem=e):(d.items[g]={key:g,elem:e,name:e.dataset.blueMetrics,detail:e.dataset.actionId},z(d,a,e.dataset.actionId));e={luggage:d,key:g};g=e;var l=g.luggage.items[g.key];
l.elem.observer||(l.elem.observer=new IntersectionObserver(h(q,g),{threshold:.85}),l.elem.observer.observe(l.ghost||l.elem),l.pageVisibilityChangeListener||(l.pageVisibilityChangeListener=h(C,g),document.addEventListener("visibilitychange",l.pageVisibilityChangeListener)));g=e.luggage.items[e.key];g.elem.clickListener||(g.elem.clickListener=h(V,e),g.elem.addEventListener("click",g.elem.clickListener))}}function y(d){var a=document.getElementById("dpx-rex-nile-search-text-input");a&&!a.hasAttribute("listenerOnErase")&&
(a.addEventListener("input",function(){!G&&0<a.value.length?G=!0:G&&0===a.value.length&&(e({schemaId:"mshop.nile.events.4",eventTimeUTC:(new Date).toISOString(),nileRequestId:D.luggage&&D.luggage.requestId,clickstreamRequestId:null,eventName:"SEARCH_INPUT_ERASE",eventDetail:"CLEAR"},"mshop.nile.events.4"),G=!1)}),a.setAttribute("listenerOnErase","true"))}function E(d,b,e){if("chunk"===b.type&&O.includes(b.lastEventId)){var n=d.chunks.markAsRendered(b);if("text"===b.lastEventId){if(b=document.getElementById("dpx-rex-nile-inline-answer-text-container")){var k=
d.answer,c=document.getElementById("ghost");if(!c){var m=document.createElement("div");a.$(m).addClass("nile-inline-ghost");c=document.createElement("div");c.id="ghost";c.className="ghost-inner-div";a.$(m).append(c);a.$(b).append(m)}k.ghost=c;d.answer.elem=b;z(d,n,"ANSWER");b=d.answer;b.observer||(b.observer=new IntersectionObserver(h(f,d),{threshold:.85}),b.visibilityChangeListener=h(g,d),document.addEventListener("visibilitychange",b.visibilityChangeListener),b.observer.observe(b.ghost||b.elem));
l(d,n,e);n=e.find("#nile-category-cards-mobile-carousel");e=e.find("[id^\x3dsection_groupId_related_questions]");H(d,n,"category_list_carousel_horizontal");H(d,e,"FOLLOW_ON_PILLS_OUTSIDE_SEEMORE")}}else"feedback_chunk"===b.lastEventId&&(z(d,n,"ANSWER_FEEDBACK"),n=e.find("#dpx-rex-nile-thumbs-up")[0],e=e.find("#dpx-rex-nile-thumbs-down")[0],n&&e&&(n.addEventListener("touchend",h(K,d),{once:!0}),e.addEventListener("touchend",h(L,d),{once:!0})))}}function T(d,a){d.chunks.addFromEvent(a)}function M(d,
a,b){d.requestEndAt=new Date;a=d.chunks.markAsRendered(a);var g=b[0]&&b[0].matches("[data-blue-request-id]")||b[0]&&b[0].querySelector("[data-blue-request-id]");g&&(d.requestId=g.dataset.blueRequestId,e({schemaId:"mshop.nile.events.4",eventTimeUTC:t(d.requestStartAt),nileRequestId:d.requestId,clickstreamRequestId:null,eventName:"INVOKE_NILE",eventDetail:d.actionId||"default_pills_fetched"},"mshop.nile.events.4"),v(d),l(d,a,b),H(d,b,"DEFAULT_PILLS"))}function K(d,a){Q(d,"THUMBS_UP")}function L(d,a){Q(d,
"THUMBS_DOWN")}function H(d,a,b){a&&(a=a.find(".a-carousel-viewport")[0])&&a.addEventListener("scroll",h(w,d,b),{once:!0})}function I(d,a){d.requestEndAt=new Date;document.removeEventListener("visibilitychange",d.visibilityChangeListenerForLatency)}function U(d){if("visible"!==document.visibilityState&&!d.requestEndAt){d.interruptedAt=new Date;var a=d.flow.toUpperCase(),b=d.chunks.maybeGetLastRendered();e({schemaId:"mshop.nile.latency.6",nileRequestId:d.requestId,elementId:a,seqId:b?b.index+1:0,requestStartTimeUTC:t(d.requestStartAt),
renderingStartTimeUTC:"",renderingEndTimeUTC:"",interruptedTimeUTC:t(d.interruptedAt)},"mshop.nile.latency.6");0<Object.keys(d.items).length||(document.removeEventListener("visibilitychange",d.visibilityChangeListenerForLatency),R(d,"PAGE_HIDDEN"))}}function A(a,b){e({schemaId:"mshop.nile.impressions.1",nileRequestId:a.requestId,elementId:"ANSWER",seqId:0,requestStartTimeUTC:t(a.requestStartAt),impressionStartTimeUTC:t(a.answer.impressingStartAt),impressionEndTimeUTC:t(a.answer.impressingEndAt),impressionEndReason:b},
"mshop.nile.impressions.1")}function B(a){var d=a.luggage;a=d.items[a.key];e({schemaId:"mshop.nile.impressions.1",nileRequestId:d.requestId,elementId:a.detail||a.name,seqId:a.chunkId||0,requestStartTimeUTC:t(d.requestStartAt),impressionStartTimeUTC:t(a.impressingStartAt),impressionEndTimeUTC:t(a.impressingEndAt),impressionEndReason:a.reason},"mshop.nile.impressions.1")}function z(a,b,g){e({schemaId:"mshop.nile.latency.6",nileRequestId:a.requestId,elementId:g,seqId:b.index,requestStartTimeUTC:t(a.requestStartAt),
renderingStartTimeUTC:t(b.renderingStartAt),renderingEndTimeUTC:t(b.renderingEndAt),interruptedTimeUTC:""},"mshop.nile.latency.6")}function v(a,b){e({schemaId:"mshop.nile.events.4",eventTimeUTC:t(a.requestStartAt),nileRequestId:a.requestId,clickstreamRequestId:null,eventName:"INVOKE_NILE_BACKEND_API",eventDetail:b},"mshop.nile.events.4")}function Q(a,b){e({schemaId:"mshop.nile.events.4",eventTimeUTC:t(new Date),nileRequestId:a.requestId,clickstreamRequestId:null,eventName:"MAIN_FEEDBACK_REQUEST",
eventDetail:b},"mshop.nile.events.4")}function V(a){var d=a.luggage.items[a.key];e({schemaId:"mshop.nile.events.4",eventTimeUTC:t(new Date),nileRequestId:a.luggage.requestId,clickstreamRequestId:null,eventName:d.name,eventDetail:d.detail},"mshop.nile.events.4")}function w(a,b){e({schemaId:"mshop.nile.events.4",eventTimeUTC:t(new Date),nileRequestId:a.requestId,clickstreamRequestId:null,eventName:"SCROLL_BUTTON_CAROUSEL",eventDetail:b},"mshop.nile.events.4")}function r(a){e({schemaId:"mshop.nile.events.4",
eventTimeUTC:(new Date).toISOString(),nileRequestId:D.luggage&&D.luggage.requestId,clickstreamRequestId:null,eventName:"SEARCH_INPUT_FOCUS",eventDetail:"TOUCH"},"mshop.nile.events.4")}function J(a){e({schemaId:"mshop.nile.events.4",eventTimeUTC:(new Date).toISOString(),nileRequestId:a.requestId,clickstreamRequestId:null,eventName:"CLEAR_BUTTON_PRESS",eventDetail:"clear_button_touch"},"mshop.nile.events.4");G=!1}function R(a,b){e({schemaId:"mshop.nile.events.4",eventTimeUTC:t(a.interruptedAt),nileRequestId:a.requestId,
clickstreamRequestId:null,eventName:"CONVERSATION_ABANDONMENT",eventDetail:b},"mshop.nile.events.4")}function N(){var a=document.getElementById("dpx-rex-nile-search-text-input");return a&&a.value||""}function S(){if("visible"!==document.visibilityState){var a=N();""!==a&&a!==D.textInputValue&&(R({interruptedAt:new Date},"QUERY_NOT_SUBMITTED"),document.removeEventListener("visibilitychange",S))}}function t(a){return a instanceof Date?a.toISOString():""}function W(a){a=(a=(a=a&&a.event&&a.event.$event&&
a.event.$event.target)&&a.closest("[data-blue-metrics]"))&&a.dataset&&a.dataset.actionId;return/^[a-z][a-z0-9]*(?:_[a-z0-9]+)*_\d_\d+$/.test(a)?a:u}function X(a){var b=a.flow;var d="answer"!==a.flow?u:a.event.triggerSource||"ENTER_PRESSED_SOURCE";return{flow:b,searchTrigger:d,actionId:W(a),chunks:{length:0,addFromEvent:function(a){var b={event:a,renderingStartAt:new Date,index:this.length};a.index=b.index;return[].push.call(this,b)},getFromEvent:function(a){return this[a.index]},maybeGetLastRendered:function(){for(var a=
this.length,b=0;b<a&&this[b].renderingEndAt;b++);return 0===b?null:this[b-1]},markAsRendered:function(a){a=this.getFromEvent(a);a.renderingEndAt=new Date;return a}},requestStartAt:new Date,requestEndAt:null,answer:{},visibleElems:{length:0,add:function(a){this[a]||[].push.call(this,a)},remove:function(a){delete this[a]}},items:{}}}var O=["text","feedback_chunk"],D={textInputValue:N()},G=!1;document.addEventListener("visibilitychange",S);return{executeAndLogMetrics:function(a,b){b=X(b);var d=D.luggage;
d&&(document.removeEventListener("visibilitychange",d.visibilityChangeListenerForLatency),d.answer&&d.answer.observer&&(d.answer.observer.unobserve(d.answer.elem),document.removeEventListener("visibilitychange",d.answer.visibilityChangeListener)));D.luggage=b;D.textInputValue=N();b={beforeChunk:h(c,b),afterChunkRender:h(E,b),afterFullRender:h(I,b),beforePillRender:h(T,b),afterPillRender:h(M,b)};a(b)},buildContext:function(a,b){return{flow:a,event:b}}}})});c.now("nile-inline-answer-streamer").execute(function(f){f||
c.when("A","nile-inline-html-truncator","nile-inline-chunk-renderer","nile-inline-loader-utils","nile-inline-csrf","nile-inline-event-stream-builder","nile-inline-uuid-generator","nile-inline-container-manager","nile-inline-search-input-button-controller","nile-inline-state-manager","dpx-rex-nile-inline-display-utils","dpx-rex-nile-inline-widget-instrumentation","dpx-nile-inline-constants","askSearch","ready").register("nile-inline-answer-streamer",function(a,c,f,h,k,b,e,x,F,q,C,g,l,y){function m(a,
b){return function(e){a===A&&(f.renderChunk(e,b),q.extend({streamingState:l.streamingState.ANSWER_LOADING}))}}function p(a){return function(){a.close();q.extend({streamingState:l.streamingState.ERROR});C.displayGenericError()}}function M(b,e){return function(){A=null;b.close();q.getState().streamingState!==l.streamingState.ERROR&&q.extend({streamingState:l.streamingState.ANSWER_RENDERED});e.afterFullRender();h.hideLoader();h.hideTrailingLoader();a.$("#dpx-rex-nile-inline-answer-text-container-sandbox")&&
0<a.$("#dpx-rex-nile-inline-answer-text-container-sandbox").length&&a.$("#dpx-rex-nile-inline-answer-text-container-sandbox").empty()}}function K(b,e){x.clearAnswerContainer();F.showClearButton();e&&(I(),q.extend({streamingState:l.streamingState.ANSWER_LOADING}),c.setIsAnswerExpanded(!1),C.hide("#dpx-rex-nile-inline-default-pills-container"),b&&(a.$("#dpx-rex-nile-search-text-input").val(b),a.$("#dpx-rex-nile-search-text-input").removeAttr("aria-describedby")),h.showLoader(),h.showTrailingLoader(),
a.$("#dpx-rex-nile-search-submit-focus-container").focus(),b=a.$("#dpx-rex-nile-loading-response-text").text(),a.$("#dpx-rex-nile-loading-response").append(b))}function L(a,b,e){a=g.buildContext(b,a);g.executeAndLogMetrics(function(a){e(a)},a)}function H(a){var b=q.getState(),e=b.streamingState===l.streamingState.ERROR;b=(b.streamingState===l.streamingState.ANSWER_RENDERED||b.streamingState===l.streamingState.ANSWER_LOADING)&&a===B;return a?e?!0:b?!1:!0:!1}function I(){r&&r.close()}var r=null,A=null;
q.extend({streamingState:l.streamingState.NOT_STARTED});var B;return{streamAnswer:function(a,g,l){var h=a.query;if(H(h)){B=h;var c=q.getState()&&q.getState().blueEnabled;K(h,c);c&&L(g,l,function(g){var l=e.generateUuid();A=l;var h=k.getRawCsrfToken("#rufusInlineCsrfTokenContainer"),c=b.buildStreamingEndpointCall("/rufus/web/renderedAnswer?");l=m(l,g);var f=p(c);g=M(c,g);c.setErrorCallback(f);c.addEventListener("CONTEXT_CHUNK",l);c.addEventListener("chunk",l);c.addEventListener("close",g);c.startPostStream(a,
h,6E4);r=c});y.executeSearch(a.asin,h,c)}},closeStream:I}})});c.now("nile-inline-request-builder").execute(function(f){f||c.when("A","nile-inline-state-manager","ready").register("nile-inline-request-builder",function(a,c){function f(a){return(a=(a=(a=a&&a.$target)&&a.closest("[data-action-url]")[0])&&a.dataset)?{actionUrl:a.actionUrl}:{}}function h(a,e,h){var b=c.getState();return Object.assign({query:a,searchSource:e,asin:b.asin,programId:"BLUE_DPX_REX"},h)}function k(){var a=c.getState();return{programId:"BLUE_DPX_REX",
conversationId:a&&a.conversationHistoryId||"",turnRequestId:a&&a.requestId||"",gmtTime:(new Date).toISOString()}}return{buildFollowOnPillClickRequest:function(a,e){return h(a,"BLUE_FOLLOWON_PILL_CLICK_SOURCE",f(e))},buildDefaultPillClickRequest:function(a,e){return h(a,"BLUE_PILL_CLICK_SOURCE",f(e))},buildSearchInputRequest:function(a){return h(a,"LIVE_SEARCH_SOURCE",{})},buildFocusedOutRequest:function(a){return h(a,"BLUE_FOCUS_OUT_SOURCE",{})},buildFeedbackRequest:function(a,e,c){return Object.assign({feedbackType:a,
mainFeedback:e},c,k())},buildDetailFeedbackRequest:function(a,e){return Object.assign({feedbackType:"DETAIL_FEEDBACK",detailFeedback:a,freeformFeedback:e},k())}}})});c.now("dpx-rex-nile-inline-display-utils").execute(function(f){f||c.when("A","nile-inline-loader-utils","ready").register("dpx-rex-nile-inline-display-utils",function(a,c){function f(b){a.$(b).removeClass(k.join(" "))}function h(b){return k.some((e)=>a.$(b).hasClass(e))}var k=["dpx-rex-nile-inline-hidden","nile-inline-hidden","askHidden"];
return{show:f,hide:function(b){a.$(b).addClass("dpx-rex-nile-inline-hidden")},isHidden:h,isButtonClickEvent:function(a){var b=a.$event;return 32===b.keyCode?(b.preventDefault(),!0):13===b.keyCode||"click"===a.type},displayGenericError:function(){h("#dpx-rex-nile-inline-answer-text-container-error")&&(f("#dpx-rex-nile-inline-answer-generic-error"),c.hideLoader(),c.hideTrailingLoader(),f("#dpx-rex-nile-inline-answer-container"),f("#nile-inline-ai-generated-label"),a.$("#dpx-rex-nile-search-text-input").attr("aria-describedby",
"dpx-rex-nile-inline-answer-generic-error"),a.$("#dpx-rex-nile-inline-answer-generic-error").attr("tabindex","0"),a.$("#dpx-rex-nile-inline-answer-generic-error").focus())}}})});c.now("dpx-rex-markdown-renderer").execute(function(f){f||c.when("jQuery").register("dpx-rex-markdown-renderer",function(a){return{renderMarkdownContent:function(c){c.find(".rufus-dpx-markdown-content[data-html-content]").each(function(){var c=a(this),h=c.attr("data-html-content");h&&(c.html(h),c.removeAttr("data-html-content"))})}}})});
c.now("nile-inline-container-manager").execute(function(f){f||c.when("A","nile-inline-feedback-actions","dpx-rex-nile-inline-display-utils","nile-inline-state-manager","dpx-nile-inline-constants","nile-inline-loader-utils","ready").register("nile-inline-container-manager",function(a,c,f,h,k,b){var e=a.$;return{clearAnswerContainer:function(){h.extend({streamingState:k.streamingState.NOT_STARTED});h.getState()&&h.getState().streamingState!==k.streamingState.ANSWER_LOADING&&f.hide("#dpx-rex-nile-inline-answer-container");
e("#dpx-rex-nile-inline-answer-text-container").empty();e("#dpx-rex-nile-inline-answer-container-truncating-sandbox").find(".a-truncate-full").empty();e("#dpx-rex-nile-inline-followon-pills-outside-container").empty();c.setFeedbackSent(!1);c.clearFeedbackContainer();e("#dpx-rex-nile-inline-answer-text-container-error").empty();b.hideLoader();b.hideTrailingLoader();f.hide("#dpx-rex-nile-inline-data-container, #dpx-rex-nile-inline-answer-text-container-error, #nile-inline-ai-generated-label, #dpx-rex-nile-inline-answer-generic-error");
e("#dpx-rex-nile-inline-answer-text-container-error, #dpx-rex-nile-inline-answer-generic-error").removeClass("nile-inline-text-container-collapsed-error")}}})});c.now("nile-inline-html-truncator").execute(function(f){f||c.when("A","nile-inline-feedback-actions","nile-inline-loader-utils","nile-inline-state-manager","dpx-nile-inline-constants","dpx-rex-nile-inline-display-utils").register("nile-inline-html-truncator",function(a,c,f,h,k,b){function e(a){var b=a.children();a[0].style.removeProperty("height");
a.find("#"+m(a,"html-truncator-marker")).addClass("dpx-rex-nile-inline-hidden");Array.from(b).forEach((a)=>{a.removeAttribute("aria-hidden")})}function m(a,b){return a[0].id?a[0].id+"-"+b:b}function p(b,g,e){e=m(b,"html-truncator-marker");var c=b.find("#"+e);0===c.length?(g=g.clone(!0),g.removeClass("nile-inline-hidden"),c=a.$(document.createElement("span")),c[0].id=e,c.addClass("nile-inline-truncation-overflow-marker"),c.append(g),b.append(c)):c.removeClass("dpx-rex-nile-inline-hidden");return c}
function q(a,b,g,e,c,h,f,k){f=a.children();e=p(a,e,c);document.createRange().selectNode(b);k=a[0].getBoundingClientRect();a[0].style.setProperty("height",k.height+"px");a=document.createElement("span");b.nodeType===Node.TEXT_NODE?"BR"===b.tagName?b.before(a):b.after(a):"BR"===b.tagName?b.before(a):b.append(a);b=k.width-e.children()[0].offsetWidth-10;k=a.offsetLeft+10;0<h&&f[g].setAttribute("aria-hidden","true");0===h&&k<b?e[0].style.setProperty("left",k+"px"):(e[0].style.removeProperty("left"),f[g].setAttribute("aria-hidden",
"true"));Array.from(f).slice(g+1).forEach((a)=>{a.id!==c&&a.setAttribute("aria-hidden","true")});a.remove()}var C=["absolute","fixed"],g=!1;return{maybeTruncate:function(a,b,c){if(g)return!1;var h=m(a,"html-truncator-marker");var k=m(a,"sandbox");var l=a.parent().find("#"+k);l[0]||(l=a.clone(),l[0].id=k,l.addClass("a-offscreen"),a.after(l));k=l;l=a.children();k.empty();var p=k[0].getBoundingClientRect().height;k.append("\x3cbr\x3e");p=k[0].getBoundingClientRect().height-p;for(var x=0,y=null,F=0,A=
0,B=!1,z=0;z<l.length;z++){var v=0;if(B)break;if(-1===C.indexOf(r.getComputedStyle(l[z]).position)&&l[z].id!==h){var u=l[z].childNodes;k.empty();for(var E=0;E<u.length;E++){var w=u[E];if(w.nodeType!==Node.TEXT_NODE||""!==w.textContent.trim()){var P=w.nodeType===Node.TEXT_NODE?"inline":r.getComputedStyle(w).display;if(P){var J=w.nodeType===Node.ELEMENT_NODE&&w.classList&&w.classList.contains("askBlueAsinFaceoutTitle");if((P.startsWith("inline")||J)&&x<=c)if(v=w.cloneNode(!0),v.removeAttribute&&v.removeAttribute("id"),
k.append(v),v=Math.round(k[0].offsetHeight/p),x+v===c)y=w,F=z;else if(x+v>c){B=!0;A=y?0:x+v-c;F=(y=y||w)?F:z;break}}}}x+=v}}B?(q(a,y,F,b,h,A,k,p),f.hideTrailingLoader()):e(a);return B},expand:e,registerTruncationActions:function(){a.declarative("nile-inline-see-more","click",function(b){e(a.$("#dpx-rex-nile-inline-answer-text-container"));g=!0;h.getState().streamingState===k.streamingState.ANSWER_LOADING&&f.showTrailingLoader()});a.declarative.create(a.$("#dpx-rex-nile-inline-see-more-action"),"nile-inline-see-more",
{})},getIsAnswerExpanded:function(){return g},setIsAnswerExpanded:function(a){g=a}}})});c.now("dpx-nile-inline-constants").execute(function(f){f||c.declare("dpx-nile-inline-constants",{streamingState:{NOT_STARTED:0,ANSWER_LOADING:1,ANSWER_RENDERED:2,ERROR:3}})});c.now("nile-inline-search-input-button-controller").execute(function(f){f||c.when("dpx-rex-nile-inline-display-utils","nile-inline-state-manager","ready").register("nile-inline-search-input-button-controller",function(a,c){return{showSubmitButton:function(){var f=
c.getState()&&c.getState().blueEnabled;a.hide("#dpx-rex-nice-clear-button");f&&a.show("#dpx-rex-nile-submit-button")},showClearButton:function(){c.getState()&&c.getState().blueEnabled&&a.hide("#dpx-rex-nile-submit-button");a.show("#dpx-rex-nice-clear-button")}}})});c.now("nile-inline-dpx-reset-widget").execute(function(f){f||c.when("A","nile-inline-default-pill-actions","nile-inline-container-manager","nile-inline-answer-streamer","nile-inline-html-truncator","nile-inline-search-input-button-controller",
"askSearch").register("nile-inline-dpx-reset-widget",function(a,c,f,h,k,b,e){return function(){h.closeStream();f.clearAnswerContainer();k.setIsAnswerExpanded(!1);c.showDefaultPills();a.$("#dpx-rex-nile-loading-response").empty();a.$("#dpx-rex-nile-search-text-input").val("");a.$("#dpx-rex-nile-search-text-input").removeAttr("aria-describedby");b.showSubmitButton();e.clearSearch()}})});c.now("nile-inline-clear-button-actions").execute(function(f){f||c.when("A","nile-inline-dpx-reset-widget","dpx-rex-nile-inline-display-utils").register("nile-inline-clear-button-actions",
function(a,c){return{registerClearButtonActions:function(){a.declarative("dpx-rex-nice-clear-button-click","click",function(){c();a.$("#dpx-rex-nile-search-text-input").focus()})}}})});c.now("nile-inline-default-pill-actions").execute(function(f){f||c.when("A","nile-inline-request-builder","nile-inline-answer-streamer","dpx-rex-nile-inline-display-utils","ready").register("nile-inline-default-pill-actions",function(a,c,f,h){return{registerDefaultPillActions:function(){a.declarative("dpx-rex-nile-inline-pill-clicked",
"click",function(a){var b=c.buildDefaultPillClickRequest(a.$target[0].value,a);f.streamAnswer(b,a,"pills")})},showDefaultPills:function(){h.show("#dpx-rex-nile-inline-default-pills-container")}}})});c.now("nile-inline-search-input-actions").execute(function(f){f||c.when("A","nile-inline-answer-streamer","nile-inline-search-input-button-controller","nile-inline-request-builder","nile-inline-state-manager","nile-inline-dpx-reset-widget","ready").register("nile-inline-search-input-actions",function(a,
c,f,h,k,b){function e(a){var b=m("#dpx-rex-nile-search-text-input");b=m.trim(b.val());b="focusout"===a.type?h.buildFocusedOutRequest(b):h.buildSearchInputRequest(b);c.streamAnswer(b,a,"answer")}var m=a.$,p=!1,q=!1;return{registerSearchInputActions:function(){var c=k.getState()&&k.getState().blueEnabled;a.declarative("dpx-rex-submit-button-clicked","click",function(a){Object.assign(a,{triggerSource:"SUBMIT_BUTTON_SOURCE"});e(a)});a.declarative("dpx-rex-submit-button-clicked","click",function(a){c&&
Object.assign(a,{triggerSource:"SUBMIT_BUTTON_SOURCE"});e(a)});c?(m("#dpx-rex-nile-search-text-input").keydown(function(a){if(a.isComposing||229===a.keyCode)q=!0;p=13===a.which}),m("#dpx-rex-nile-search-text-input").focusout(function(a){a=a.relatedTarget;p||m(a).is("input.a-button-input")||"dpx-rex-nile-submit-button-announce"===a.id||m("#dpx-rex-nile-search-text-input").trigger({type:"keyup",which:13,keyCode:13});p=!1}),m("#dpx-rex-nile-search-text-input").keyup(function(a){""===a.target.value&&
b();q?(q=!1,f.showSubmitButton()):13!==a.which?f.showSubmitButton():(m("#dpx-rex-nile-search-text-input").blur(),e(a))})):m("#dpx-rex-nile-search-text-input").keyup(function(a){""===a.target.value&&b();13===a.which&&e(a)})}}})});c.now("nile-inline-feedback-actions").execute(function(f){f||c.when("A","nile-inline-csrf","nile-inline-request-builder","a-popover","dpx-rex-nile-inline-display-utils","a-button","ready").register("nile-inline-feedback-actions",function(a,c,f,h,k,b){function e(){k.hide("#ask-blue-ai-generated-label");
k.show("#ask-feedback-success-text-container");setTimeout(()=>{const b=a.$("#ask-feedback-success-text-container").text().trim();a.$("#ask-feedback-status-announcer").text(b)},500)}function m(b){"THUMBS_UP"===b?(k.hide("#thumbs-up-not-selected"),k.show("#thumbs-up-selected"),a.$("#ask-blue-thumbs-up").attr("aria-disabled","true"),a.$("#ask-blue-thumbs-up").removeAttr("tabindex"),a.$("#ask-blue-thumbs-down").remove(),l.forEach(k.hide),e()):(k.hide("#thumbs-down-not-selected"),k.show("#thumbs-down-selected"),
0<a.$("#a-popover-ask-blue-detail-feedback").length?h.get(a.$("#ask-blue-detail-feedback-action")).show():k.show("#ask-blue-feedback-box"))}function p(){a.$("#ask-blue-feedback-box").remove();h.remove("ask-blue-detail-feedback");l.forEach(k.hide);a.$("#ask-blue-thumbs-up").remove();a.$("#ask-blue-thumbs-down").attr("aria-disabled","true").focus();e()}function q(b){a.$.ajax({url:"/rufus/web/feedback?",data:b,dataType:"json",type:"POST",timeout:1E4,headers:{"anti-csrftoken-a2z":c.getRawCsrfToken("#rufusInlineCsrfTokenContainer"),
"Content-Type":"application/json"}})}function r(){var b=a.$(".ask-blue-feedback-checkbox:checked").map(function(b,c){return a.$(c).val()}).get(),c;a.$("#ask-blue-feedback-option-freetext").is(":checked")&&(c=a.$("#ask-blue-feedback-textbox").val().substring(0,500));q(JSON.stringify(f.buildDetailFeedbackRequest(b,c)))}var g=!1,l=["#thumbs-up-not-selected","#thumbs-down-not-selected","#ask-blue-space-between-thumbs"];return{registerFeedbackActions:function(){a.declarative("ask-blue-thumbs-up-click",
"click keydown",function(a){!g&&k.isButtonClickEvent(a)&&(q(JSON.stringify(f.buildFeedbackRequest("MAIN_FEEDBACK","THUMBS_UP",void 0))),m("THUMBS_UP"),g=!0)});a.declarative("ask-blue-thumbs-down-click","click keydown",function(a){!g&&k.isButtonClickEvent(a)&&(q(JSON.stringify(f.buildFeedbackRequest("MAIN_FEEDBACK","THUMBS_DOWN",void 0))),m("THUMBS_DOWN"),g=!0)});a.declarative("ask-blue-feedback-option-click","click",function(){1<=a.$(".ask-blue-feedback-checkbox:checked").length?(b("#ask-blue-feedback-submit").enable(),
a.$("#ask-blue-feedback-submit").prop("disabled",!1)):(b("#ask-blue-feedback-submit").disable(),a.$("#ask-blue-feedback-submit").prop("disabled",!0));a.$("#ask-blue-feedback-option-freetext").is(":checked")?k.show("#ask-blue-feedback-container"):k.hide("#ask-blue-feedback-container")});a.declarative("ask-blue-feedback-close-click","click keydown",function(a){k.isButtonClickEvent(a)&&p()});a.declarative("ask-blue-feedback-cancel-click","click",function(){p()});a.declarative("ask-blue-feedback-submit-click",
"click",function(){r();p()})},setFeedbackSent:function(a){g=a},hideFeedback:function(){k.hide("#dpx-rex-nile-inline-feedback-container")},showFeedback:function(){k.show("#dpx-rex-nile-inline-feedback-container")},clearFeedbackContainer:function(){a.$("#dpx-rex-nile-inline-feedback-container").empty()}}})});c.now("nile-inline-followon-pill-actions").execute(function(f){f||c.when("A","jQuery","nile-inline-request-builder","nile-inline-answer-streamer","ready").register("nile-inline-followon-pill-actions",
function(a,c,f,h){return{registerFollowOnPillActions:function(){a.declarative("followon-pill-click","click keypress",function(c){var b=f.buildFollowOnPillClickRequest(c.$target[0].value,c);h.streamAnswer(b,c,"pills");b=a.$("#dpx-rex-nice-widget-container");c=b.offset().top;b=c+b.outerHeight();var e=a.$(r).scrollTop(),k=e+a.$(r).height();(b<e||c>k)&&a.$(r).scrollTop(c-(0<a.$(".s-mobile-toolbar-offscreen").length?0:a.$(".s-mobile-toolbar-sticky")?a.$(".s-mobile-toolbar-sticky").outerHeight():0))})}}})});
c.now("nile-inline-widget").execute(function(f){f||c.when("A","jQuery","nile-inline-feedback-actions","nile-inline-default-pill-actions","nile-inline-html-truncator","nile-inline-answer-chunk-handler","nile-inline-followon-pill-actions","dpx-rex-nile-inline-widget-instrumentation","nile-inline-clear-button-actions","nile-inline-search-input-actions","nile-inline-collapse-bottom-sheet","nile-inline-element-prefix-utils","askSearch","askPostQuestion","nile-inline-state-manager","ready").register("nile-inline-widget",
function(a,c,f,h,k,b,e,r,u,q,C,g,l,y,E){g.setupElementPrefix("dpx-rex");f.registerFeedbackActions();h.registerDefaultPillActions();k.registerTruncationActions();e.registerFollowOnPillActions();u.registerClearButtonActions();C.registerCollapseBottomSheetActions();q.registerSearchInputActions();l.setupExpander();y.registerDeclarativeActions();(a=E.getState())&&a.blueEnabled&&(a=r.buildContext("pills"),r.executeAndLogMetrics(function(a){var b={type:"default_pills"};a.beforePillRender(b);var e=c("#dpx-rex-nile-inline-default-pills-container");
e=c(e);a.afterPillRender(b,e)},a))})})});
/* ******** */
