window.aui.amd_define("@amzn/kata-web-framework-logger",["exports"],function(r){"use strict";const l=()=>{var n;return(n=!1)!==null&&n!==void 0?n:!1},d=()=>!0,g=()=>window.ueLogError,m=n=>console[n];function t({code:n,e:o,context:e,level:w="ERROR"}){const u=g(),c=m(E[w]);if(u&&d()){const i={logLevel:w,attribution:"HtmlKataWebFrameworkJs",message:n};o instanceof Error?u(o,i):u(i),l()&&c(n,o,{...i,...e})}else l()?c(n,o,e):c(n,o)}const E={FATAL:"error",ERROR:"error",WARN:"warn"},b=(n,o,e)=>{t({code:n,e:o,context:e,level:"ERROR"})},a=(n,o,e)=>{t({code:n,e:o,context:e,level:"WARN"})},I=(n,o,e)=>{t({code:n,e:o,context:e,level:"FATAL"})},L=()=>{},R=(n,o,e)=>{o.has(n)?a(e):o.add(n)};let f=!1;const s=()=>window.fm?window.fm:(f||(a("K067"),f=!0),{recordInstrumentationEvent:()=>{},now:()=>0});function v(n,o){const e=s();e.recordInstrumentationEvent(n,o!=null?o:e.now())}const A=()=>typeof window.uex!="function"?()=>{}:window.uex,K=()=>!window.ue||typeof window.ue.count!="function"?()=>{}:window.ue.count;function k(){A()("ld","kwf",{wb:1})}function y(){K()("kwf.enabled",1)}r.countKwfEnabled=y,r.error=b,r.fatal=I,r.fmInstance=s,r.log=t,r.recordMetric=v,r.reportKwfLoaded=k,r.timing=L,r.warn=a,r.warnIfDuplicate=R,Object.defineProperty(r,Symbol.toStringTag,{value:"Module"})});/*! _CB1_ */

/* ******** */
window.aui.amd_define("@amzn/kata-web-framework-register",["exports","@amzn/kata-web-framework-logger"],function(s,c){"use strict";const l=Object.create(null),R=new Set,K=e=>{const r=e.split(":")[1];return(r==null?void 0:r.split(",")[0])||""},y=(e,r)=>{var n;return l[e]=(n=l[e])!==null&&n!==void 0?n:C(r,e),l[e].config!==r&&c.log({code:"K031",context:{uuid:e,config:r}}),l[e]},v=(e,...r)=>y(U(e,...r),e),C=(e,r)=>{let n,a,i=!1,o;const w=()=>{const t=K(r);return R.has(t)?(R.delete(t),c.warn("K079",null,{uuid:r}),!0):!1},h=t=>{var f,m,d;if(n){if(w())return;c.warn((f=e.diagnostics.alreadyProvidedWarn)!==null&&f!==void 0?f:"K005",null,{uuid:r});return}if(a){if(w())return;c.warn((m=e.diagnostics.alreadyFailedWarn)!==null&&m!==void 0?m:"K006",null,{uuid:r});return}if(i){c.error((d=e.diagnostics.alreadyReleasedWarn)!==null&&d!==void 0?d:"K009",null,{uuid:r});return}t()},k=t=>{h(()=>{n=t})},B=t=>{h(()=>{a=t})},T=()=>{if(i)return;o=void 0,n=void 0,a=void 0,i=!0;const t=K(r);t&&R.add(t),delete l[r]},p={uuid:r,provide:k,fail:B,release:T,assertReleased:()=>{if(!i&&!e.willNotBeReleased)throw new Error("K057")},promise:()=>(o||(a?o=Promise.reject(a):n?o=Promise.resolve(n):i?o=Promise.reject(new Error("K058")):o=new Promise((t,f)=>{const m=M(e,r),d=()=>{m.forEach(u=>clearTimeout(u))};p.provide=u=>{k(u),t(u),d()},p.fail=u=>{B(u),f(u),d()},p.release=()=>{T(),f(new Error("K058")),d()}})),e.singleConsumer&&(o=o.finally(T)),o),config:e};return p},U=(e,...r)=>`${e.namespace}:${r.join(",")}`,g=e=>{for(const r of e)l[r]&&l[r].release()},j=e=>{for(const r in l){const n=r;e&&l[n].assertReleased(),l[n].release(),delete l[n]}},E=()=>{R.clear()},N=3e3,I=3e4,M=({timeouts:e,diagnostics:r},n)=>{var a,i;const o=setTimeout(()=>{c.warn(r.timeout,null,{uuid:n})},(a=e==null?void 0:e.warn)!==null&&a!==void 0?a:N),w=setTimeout(()=>{c.error(r.timeout,null,{uuid:n})},(i=e==null?void 0:e.error)!==null&&i!==void 0?i:I);return[o,w]},_={namespace:"ext",diagnostics:{timeout:"K059"},willNotBeReleased:!0},P={namespace:"template",diagnostics:{timeout:"K001"},willNotBeReleased:!0},S=(e,r)=>v(P,e).provide(r),z=e=>v(P,e).promise(),A=(e,r)=>v(_,e).provide(r),O=e=>v(_,e).promise();s.createUuid=U,s.externalLookup=O,s.externalRegister=A,s.lookup=z,s.register=S,s.release=g,s.track=y,s.trackByIds=v,s.unsafeClearReleasedRenderUuids=E,s.unsafeReleaseAll=j,Object.defineProperty(s,Symbol.toStringTag,{value:"Module"})});/*! _CB1_ */

/* ******** */
window.aui.amd_define("@amzn/kata-web-framework-runtime-functions",["@amzn/kata-web-framework-runtime-utils"],function(n){"use strict";const t=()=>{},e=i=>i;return()=>({unsupportedFn:n.unsupportedFn,voidFn:t,identityFn:e})});/*! _CB1_ */

/* ******** */
window.aui.amd_define("@amzn/kata-web-framework-runtime-utils",["exports","@amzn/kata-web-framework-logger"],function(n,t){"use strict";const c=(...r)=>r.flat(1/0).join(""),s=(...r)=>r.join(" ").trim().replace(/\s+/g," "),u=(r,e)=>(r%e+e)%e,l=(r,e)=>({get:()=>r.read(e),set:i=>{r.defer(()=>{try{r.write(e,i)}catch(g){t.error("K063",g,{value:e,newValue:i})}})}}),f=(r,e)=>({get:()=>r,set:e}),m=r=>({discriminator:o(r),value:r,reflection:typeof r}),o=r=>{var e;return(e=r==null?void 0:r.__type)!==null&&e!==void 0?e:r==null?void 0:r.runtimeDataType},y=(r,e)=>e.map(i=>`${i}=${a(r,i)}`).join("&"),a=(r,e)=>{switch(e){case"discriminator":return o(r);case"value":return r;case"reflection":return typeof r;case"length":return Array.isArray(r)?r.length:null}},d=()=>{t.error("K041")};n.box=l,n.classes=s,n.describeExpr=y,n.discriminators=m,n.flattenToString=c,n.mod=u,n.reBox=f,n.unsupportedFn=d,Object.defineProperty(n,Symbol.toStringTag,{value:"Module"})});/*! _CB1_ */

/* ******** */
